# sOn Messenger TURN server
listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
realm=sonchat.uk
server-name=sonchat.uk
# Static user credentials
user=son:son-turn-2026
# Log level
log-file=/var/log/turnserver.log
verbose
# Security
no-multicast-peers
no-cli
